---
# Handler para configuraciones de servidor de base de datos en CentOS

# Reiniciar y dejar habilitado el servicio “mariadb”
- name: restart mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
    enabled: yes