---
# Este libro de tareas está hecho con mucho amor y sangre!!! - Hansi
# Lanzador de tareas de acuerdo con distribución, grupo de equipos y etiquetas

- name: Aplicar configuración básica a todos los equipos
  hosts: all
  become: yes
  tags:
   - basic
  roles: 
   - common

- name: Instalación y configuración de servidor web para equipos webservers
  hosts: webservers
  become: yes
  tags:
   - web
  roles:
   - role: web

- name: Instalación y configuración de servidor de base de datos para equipos dbservers
  hosts: dbservers
  become: yes
  tags:
   - db
  roles:
   - role: db