---
# Estas tareas se encargan de descargar la última versión de la aplicación y de configurarla.

- name: Copiar código del repositorio
  ansible.builtin.git: 
    repo: "{{ repository }}"
    dest: /var/www/html/

- name: Configurar archivo index.php
  ansible.builtin.template:
    src: index.php.j2 
    dest: /var/www/html/index.php

- name: Configurar httpd para que use, por defecto, el archivo index.php en vez de index.html
  ansible.builtin.lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: '^(.*)DirectoryIndex index.html(.*)$' 
    line: "    DirectoryIndex index.php"
    state: present
    backrefs: yes
  notify: httpd restart