---
# Configuración e instalación de servidor web para CentOS

- name: Instalar httpd y php
  ansible.builtin.yum: 
    name: "{{ item }}"
    state: latest
  loop:
   - httpd
   - php
   - php-mysqlnd

- name: Instalar última versión de git
  ansible.builtin.yum: 
    name: git
    state: latest

- name: Crear regla en firewalld, para aceptar conexiones entrantes a el o los puertos definidos en la sección de variables
  ansible.posix.firewalld: 
    service: "{{ httpd_service }}"
    permanent: yes 
    state: enabled 
    immediate: yes

- name: httpd iniciado y habilitado
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: yes

- name: Configurar selinux para permitir conexiones de httpd a equipos remotos
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db 
    state: true 
    persistent: yes