---
# Configuración básica para todos los equipos CentOS 

 - name: Verificar que epel este instalado
   ansible.builtin.yum:
     name: epel-release
     state: present 

 - name: Verificar que crhonid no esté instalado en CentOS
   ansible.builtin.yum:
     name: chronyd
     state: absent

 - name: Instalar paquetes en CentOS
   ansible.builtin.yum:
     name: "{{ item }}"
     state: present 
   loop:
    - systemd-timesyncd
    - libselinux
    - libsemanage
    - policycoreutils
    - policycoreutils-python-utils
   notify: service systemd-timesyncd

 - name: Configurar zona horaria
   community.general.timezone:
     name: "{{ timezone }}"
   notify: service systemd-timesyncd

 - name: Cargar los servidores “ntp” en “/etc/systemd/timesyncd.conf”
   lineinfile:
    path: /etc/systemd/timesyncd.conf
    line: "NTP={{ ntpserver1 }} {{ ntpserver2 }} {{ ntpserver2 }}"
    state: present
   notify: service systemd-timesyncd
   
 - name: Verificar que firewalld este iniciado y habilitado 
   ansible.builtin.systemd:
     name: firewalld
     state: started
     enabled: yes

 - name: Habilitar “selinux” en modo estricto con etiquetado
   ansible.posix.selinux:
    policy: targeted
    state: enforcing