---
# Handler para configuraciones de servidor web en CentOS

# Reiniciar y dejar habilitado el servicio “httpd”
- name: httpd restart
  ansible.builtin.systemd:
    name: httpd
    state: restarted
    enabled: yes