---
# Configuración e instalación de servidor de base de datos para CentOS

- name: Instalar última versión MariaDB y herramientas
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  loop:
   - mariadb-server
   - python3-PyMySQL

- name: Configurar selinux para permitir conexiones a MariaDB desde cualquier parte
  ansible.posix.seboolean:
    name: mysql_connect_any 
    state: yes 
    persistent: yes

- name: Crear archivo de configuración para MariaDB
  ansible.builtin.template:
   src: my.cnf.j2 
   dest: /etc/my.cnf
  notify:
   - restart mariadb

- name: Crear archivo de log para MariaDB
  ansible.builtin.file:
    path: /var/log/mysqld.log 
    state: touch 
    owner: mysql 
    group: mysql 
    mode: 0775

- name: Crear archivo de PID para MariaDB
  ansible.builtin.file:
    path: /var/run/mysqld 
    state: directory 
    owner: mysql 
    group: mysql 
    mode: 0775
  notify:
   - restart mariadb    

- name: Iniciar y habilitar MariaDB
  ansible.builtin.systemd: 
    name: mariadb 
    state: started 
    enabled: yes

- name: Crear regla en firewalld, para aceptar conexiones entrantes a MariaDB
  ansible.posix.firewalld: 
    port: "{{ mysql_port }}/tcp"
    permanent: yes 
    state: enabled 
    immediate: yes

- name: Crear base de datos para la aplicación
  community.mysql.mysql_db:
    name: "{{ dbname }}" 
    state: present

- name: Crear usuario para la base de datos, con permisos de acceso desde cualquier dirección
  community.mysql.mysql_user: 
    name: "{{ dbuser }}" 
    password: "{{ upassword }}" 
    priv: "*.*:ALL"
    host: '%'
    state: present