---
# Handler para tareas básicas en CentOS

# Reiniciar y dejar habilitado el servicio “timesyncd”
- name: service systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: yes