---
# Configuración e instalación de servidor web para Ubuntu

- name: Instalar apache2, php y herramientas
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
   - apache2
   - php
   - libapache2-mod-php
   - php-mysql
   - libapache2-mod-apparmor
   - apparmor-utils

- name: Instalar última versión de git
  ansible.builtin.apt:
    name: git
    state: latest

- name: Crear regla en ufw, para aceptar conexiones a “Apache”
  community.general.ufw:
    rule: allow
    state: enabled
    name: "Apache"
  notify: restart ufw
    
- name: apache2 iniciado y habilitado
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes

- name: Configurar apparmor para apache
  command:
     cmd: "{{ item }}"
  loop:
   - aa-enforce /etc/apparmor.d/usr.sbin.apache2
   - a2enmod mpm_prefork
   - a2enmod apparmor
  notify: restart apache2